# Generated by Django 6.0 on 2025-12-12 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='productModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New product', max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product-images/')),
                ('category', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to='Products.categorymodel')),
            ],
        ),
    ]
