# Generated by Django 6.0 on 2025-12-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_multipleimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimages',
            name='images',
            field=models.ImageField(blank=True, default='', null=True, upload_to='product-images/'),
        ),
    ]
