# Generated by Django 6.0 on 2025-12-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='product-images/'),
        ),
    ]
