# Generated by Django 6.0 on 2025-12-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_productmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='product-images/'),
        ),
    ]
