# Generated by Django 6.0 on 2025-12-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_productmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multipleimages',
            old_name='images',
            new_name='extra_images',
        ),
    ]
