# Generated by Django 6.0 on 2025-12-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_rename_images_multipleimages_extra_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='price',
            new_name='price_in',
        ),
    ]
